#!/usr/bin/env python3
"""Generate CycloneDX SBOM companion metadata.

The generated document deliberately does *not* claim that dependencies were
scanned or that vulnerabilities are not exploitable. It links release metadata
to the SBOM and records that an exploitability assessment is still required.
A real VEX assertion must be produced by a vulnerability scanner plus a
reviewed per-vulnerability assessment process.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path
import uuid


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--sbom",
        default="target/taxonomy-sbom.json",
        help="Path to the CycloneDX JSON SBOM generated by the Maven build.",
    )
    parser.add_argument(
        "--output",
        default="target/taxonomy-vex.json",
        help="Path to write the CycloneDX SBOM companion document.",
    )
    args = parser.parse_args()

    sbom_path = Path(args.sbom)
    output_path = Path(args.output)
    if not sbom_path.is_file():
        print(f"SBOM file not found at {sbom_path}; skipping companion generation")
        return

    sbom = json.loads(sbom_path.read_text(encoding="utf-8"))
    companion = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.6",
        "version": 1,
        "serialNumber": f"urn:uuid:{uuid.uuid4()}",
        "metadata": {
            "timestamp": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "tools": {
                "components": [
                    {
                        "type": "application",
                        "name": "taxonomy-sbom-companion-generator",
                        "version": "2.0.0",
                        "description": (
                            "Links Taxonomy release metadata to its SBOM without "
                            "making vulnerability or exploitability assertions"
                        ),
                    }
                ]
            },
            "component": {
                "type": "application",
                "name": "Taxonomy Architecture Analyzer",
                "bom-ref": "taxonomy-app",
                "purl": "pkg:github/carstenartur/Taxonomy",
                "supplier": {
                    "name": "Carsten Hammer",
                    "url": ["https://github.com/carstenartur"],
                },
            },
            "properties": [
                {
                    "name": "taxonomy:sbom-ref",
                    "value": sbom.get("serialNumber", "unknown"),
                },
                {
                    "name": "taxonomy:sbom-version",
                    "value": str(sbom.get("version", 1)),
                },
                {
                    "name": "vex:assessment-status",
                    "value": "not-assessed",
                },
                {
                    "name": "vex:policy",
                    "value": (
                        "No vulnerability scan or exploitability assessment is represented "
                        "by this document. An empty vulnerabilities array is not evidence "
                        "that the release has no known or exploitable vulnerabilities."
                    ),
                },
            ],
        },
        "vulnerabilities": [],
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(companion, indent=2) + "\n", encoding="utf-8")
    print(f"SBOM companion document generated: {output_path}")
    print("  Vulnerability assessment: not-assessed")
    print(f"  SBOM serial: {sbom.get('serialNumber', 'N/A')}")
    print(f"  Components in SBOM: {len(sbom.get('components', []))}")


if __name__ == "__main__":
    main()
