#!/usr/bin/env python3
"""Generate a minimal CycloneDX VEX document for the release SBOM."""

from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path
import uuid


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--sbom",
        default="target/taxonomy-sbom.json",
        help="Path to the CycloneDX JSON SBOM generated by the Maven build.",
    )
    parser.add_argument(
        "--output",
        default="target/taxonomy-vex.json",
        help="Path to write the generated VEX document.",
    )
    args = parser.parse_args()

    sbom_path = Path(args.sbom)
    output_path = Path(args.output)
    if not sbom_path.is_file():
        print(f"SBOM file not found at {sbom_path}; skipping VEX generation")
        return

    sbom = json.loads(sbom_path.read_text(encoding="utf-8"))
    vex = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.6",
        "version": 1,
        "serialNumber": f"urn:uuid:{uuid.uuid4()}",
        "metadata": {
            "timestamp": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "tools": {
                "components": [
                    {
                        "type": "application",
                        "name": "taxonomy-vex-generator",
                        "version": "1.0.0",
                        "description": "Automated VEX generator for Taxonomy Architecture Analyzer",
                    }
                ]
            },
            "component": {
                "type": "application",
                "name": "Taxonomy Architecture Analyzer",
                "bom-ref": "taxonomy-app",
                "purl": "pkg:github/carstenartur/Taxonomy",
                "supplier": {
                    "name": "Carsten Hammer",
                    "url": ["https://github.com/carstenartur"],
                },
            },
            "properties": [
                {
                    "name": "vex:sbom-ref",
                    "value": sbom.get("serialNumber", "unknown"),
                },
                {
                    "name": "vex:sbom-version",
                    "value": str(sbom.get("version", 1)),
                },
                {
                    "name": "vex:assessment-status",
                    "value": "automated-initial",
                },
                {
                    "name": "vex:policy",
                    "value": "No known exploitable vulnerabilities at time of build. Runtime dependency status is derived from the generated release SBOM.",
                },
            ],
        },
        "vulnerabilities": [],
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(vex, indent=2) + "\n", encoding="utf-8")
    print(f"VEX document generated: {output_path}")
    print(f"  SBOM serial: {sbom.get('serialNumber', 'N/A')}")
    print(f"  Components in SBOM: {len(sbom.get('components', []))}")


if __name__ == "__main__":
    main()
