{{/* One effective environment for both existing and guided installations. */}}
{{- define "taxonomy.environment" -}}
{{- $config := deepCopy .Values.config -}}
{{- $secrets := deepCopy .Values.secretEnv -}}
{{- $authentication := .Values.authentication | default dict -}}
{{- $mode := get $authentication "mode" | default "existing" -}}
{{- $database := .Values.database | default dict -}}
{{- if not (has $mode (list "existing" "local" "keycloak")) -}}
{{- fail "authentication.mode must be existing, local or keycloak" -}}
{{- end -}}
{{- range $setting, $env := dict "url" "SPRING_DATASOURCE_URL" "username" "SPRING_DATASOURCE_USERNAME" -}}
{{- $value := get $database $setting | default "" -}}
{{- if $value -}}
{{- if hasKey $config $env -}}{{- fail (printf "database.%s conflicts with config.%s; configure this setting in one place" $setting $env) -}}{{- end -}}
{{- if and (eq $setting "url") (or (contains "@" $value) (regexMatch "(?i)(password|sslpassword|user)\\s*=" $value)) -}}
{{- fail "database.url must not contain credentials; use the selected Secret instead" -}}
{{- end -}}
{{- $_ := set $config $env $value -}}
{{- $_ := unset $secrets $env -}}
{{- end -}}
{{- end -}}
{{- if ne $mode "existing" -}}
{{- if empty .Values.existingSecret -}}{{- fail "Guided setup requires existingSecret; credentials are never generated by the chart" -}}{{- end -}}
{{- $profiles := list -}}
{{- range splitList "," (get $config "SPRING_PROFILES_ACTIVE" | default "postgres,kubernetes") -}}
{{- if trim . -}}{{- $profiles = append $profiles (trim .) -}}{{- end -}}
{{- end -}}
{{- if or (and (eq $mode "local") (has "keycloak" $profiles)) (and (eq $mode "keycloak") (has "local-user-management" $profiles)) -}}
{{- fail "The selected authentication mode conflicts with config.SPRING_PROFILES_ACTIVE" -}}
{{- end -}}
{{- if eq $mode "local" -}}
{{- $_ := set $config "SPRING_PROFILES_ACTIVE" (join "," (uniq (concat $profiles (list "production" "local-user-management")))) -}}
{{- $_ := set $config "TAXONOMY_SECURITY_LOCAL_USERS_ENABLED" "true" -}}
{{- if not (hasKey $secrets "TAXONOMY_ADMIN_PASSWORD") -}}{{- fail "Local setup requires a TAXONOMY_ADMIN_PASSWORD Secret mapping" -}}{{- end -}}
{{- else -}}
{{- $_ := set $config "SPRING_PROFILES_ACTIVE" (join "," (uniq (concat $profiles (list "production" "keycloak")))) -}}
{{- $_ := set $config "TAXONOMY_SECURITY_LOCAL_USERS_ENABLED" "false" -}}
{{- $_ := unset $secrets "TAXONOMY_ADMIN_PASSWORD" -}}
{{- $issuer := get $config "KEYCLOAK_ISSUER_URI" | default "" -}}
{{- if not (regexMatch "^https://[^/@?#[:space:]]+(/[^?#[:space:]]*)?$" $issuer) -}}
{{- fail "Guided Keycloak setup requires config.KEYCLOAK_ISSUER_URI over HTTPS without credentials, query or fragment" -}}
{{- end -}}
{{- if empty (get $config "KEYCLOAK_CLIENT_ID") -}}{{- fail "Guided Keycloak setup requires config.KEYCLOAK_CLIENT_ID" -}}{{- end -}}
{{- if empty (get $config "KEYCLOAK_JWK_SET_URI") -}}
{{- $_ := set $config "KEYCLOAK_JWK_SET_URI" (printf "%s/protocol/openid-connect/certs" (trimSuffix "/" $issuer)) -}}
{{- end -}}
{{- $_ := set $secrets "KEYCLOAK_CLIENT_SECRET" (dict "key" (get $authentication "keycloakClientSecretKey" | default "KEYCLOAK_CLIENT_SECRET") "optional" false) -}}
{{- end -}}
{{- range .Values.extraEnv -}}
{{- if or (hasKey $config .name) (hasKey $secrets .name) -}}
{{- fail "Guided setup does not allow extraEnv to shadow its config or Secret mappings" -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- range $key, $value := $config }}
- name: {{ $key }}
  value: {{ $value | quote }}
{{- end }}
{{- if .Values.existingSecret }}
{{- range $envName, $secretSpec := $secrets }}
- name: {{ $envName }}
  valueFrom:
    secretKeyRef:
      name: {{ $.Values.existingSecret | quote }}
      key: {{ $secretSpec.key | quote }}
      optional: {{ $secretSpec.optional }}
{{- end }}
{{- end }}
{{- with .Values.extraEnv }}
{{ toYaml . }}
{{- end }}
{{- end -}}
