package com.taxonomy.shared.config;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class SchemaContractMigrationRepositoryBackfillTest {

    @Test
    void mapsWorkspaceRowsToTheirSourceRepositoryAndCentralRowsToPrimary() throws Exception {
        DataSource dataSource = createLegacySchema();
        insertRepositories(dataSource);
        execute(dataSource, """
                insert into user_workspace (workspace_id, source_repository_id)
                values ('workspace-b', 'repo-b')
                """);
        insertLegacyRelation(dataSource, null, "__shared__", 1L);
        insertLegacyRelation(dataSource, "  workspace-b  ", "  workspace-b  ", 2L);

        SchemaContractMigration migration = new SchemaContractMigration(dataSource);
        migration.migrate();
        migration.migrate();

        assertThat(singleString(dataSource, """
                select repository_id
                from taxonomy_relation
                where workspace_id is null
                """))
                .isEqualTo("repo-a");
        assertThat(singleString(dataSource, """
                select repository_id
                from taxonomy_relation
                where workspace_id = 'workspace-b'
                """))
                .isEqualTo("repo-b");
        assertThat(singleString(dataSource, """
                select workspace_scope_key
                from taxonomy_relation
                where workspace_id = 'workspace-b'
                """))
                .isEqualTo("workspace-b");

        execute(dataSource, """
                insert into taxonomy_relation (
                    repository_id,
                    source_node_id,
                    target_node_id,
                    relation_type,
                    workspace_scope_key)
                values ('repo-b', 1, 2, 'SUPPORTS', '__shared__')
                """);

        assertThatThrownBy(() -> execute(dataSource, """
                insert into taxonomy_relation (
                    repository_id,
                    source_node_id,
                    target_node_id,
                    relation_type,
                    workspace_scope_key)
                values ('repo-a', 1, 2, 'SUPPORTS', '__shared__')
                """))
                .isInstanceOf(SQLException.class);

        assertThatThrownBy(() -> execute(dataSource, """
                insert into taxonomy_relation (
                    repository_id,
                    source_node_id,
                    target_node_id,
                    relation_type,
                    workspace_scope_key)
                values ('missing-repository', 9, 10, 'DEPENDS_ON', '__shared__')
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void refusesWorkspaceRowsWithoutSourceRepositoryProvenance() throws Exception {
        DataSource dataSource = createLegacySchema();
        insertRepositories(dataSource);
        insertLegacyRelation(
                dataSource,
                "workspace-without-metadata",
                "workspace-without-metadata",
                20L);

        assertThatThrownBy(() -> new SchemaContractMigration(dataSource).migrate())
                .isInstanceOf(IllegalStateException.class)
                .hasStackTraceContaining("workspace source repository provenance is missing or ambiguous");
    }

    private static DataSource createLegacySchema() throws SQLException {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.hsqldb.jdbc.JDBCDriver");
        dataSource.setUrl("jdbc:hsqldb:mem:schema-contract-"
                + UUID.randomUUID().toString().replace("-", ""));
        dataSource.setUsername("SA");
        dataSource.setPassword("");

        execute(dataSource, """
                create table system_repository (
                    repository_id varchar(255) primary key,
                    primary_repo boolean not null)
                """);
        execute(dataSource, """
                create table user_workspace (
                    workspace_id varchar(255) primary key,
                    source_repository_id varchar(255))
                """);
        execute(dataSource, """
                create table taxonomy_relation (
                    id bigint generated by default as identity primary key,
                    repository_id varchar(255),
                    source_node_id bigint not null,
                    target_node_id bigint not null,
                    relation_type varchar(255) not null,
                    workspace_id varchar(255),
                    workspace_scope_key varchar(255),
                    constraint uk_taxonomy_relation_scope
                        unique (source_node_id, target_node_id, relation_type, workspace_scope_key))
                """);
        return dataSource;
    }

    private static void insertRepositories(DataSource dataSource) throws SQLException {
        execute(dataSource, """
                insert into system_repository (repository_id, primary_repo)
                values ('repo-a', true), ('repo-b', false)
                """);
    }

    private static void insertLegacyRelation(
            DataSource dataSource,
            String workspaceId,
            String workspaceScopeKey,
            long sourceId) throws SQLException {
        String workspace = workspaceId == null ? "null" : "'" + workspaceId + "'";
        execute(dataSource, """
                insert into taxonomy_relation (
                    source_node_id,
                    target_node_id,
                    relation_type,
                    workspace_id,
                    workspace_scope_key)
                values (%d, %d, 'SUPPORTS', %s, '%s')
                """.formatted(sourceId, sourceId + 1, workspace, workspaceScopeKey));
    }

    private static String singleString(DataSource dataSource, String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery(sql)) {
            result.next();
            return result.getString(1);
        }
    }

    private static void execute(DataSource dataSource, String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
