package com.taxonomy;

import com.taxonomy.dto.*;
import com.taxonomy.service.ArchitectureReportService;
import com.taxonomy.service.ExplanationTraceService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Tests for Architecture Report Export (Feature 7) and
 * Structured Explainable Reasoning (Feature 6b).
 */
@SpringBootTest
@AutoConfigureMockMvc
class ArchitectureReportTests {

    @Autowired private MockMvc mockMvc;
    @Autowired private ArchitectureReportService reportService;
    @Autowired private ExplanationTraceService traceService;

    // ── Report Service Tests ──────────────────────────────────────────────────

    @Test
    void generateReportWithEmptyScoresReturnsEmptyReport() {
        ArchitectureReport report = reportService.generateReport(Map.of(), "test requirement", 50);

        assertThat(report.getBusinessText()).isEqualTo("test requirement");
        assertThat(report.getGeneratedAt()).isNotNull();
        assertThat(report.getArchitectureView()).isNotNull();
        assertThat(report.getGapAnalysis()).isNotNull();
        assertThat(report.getPatternDetection()).isNotNull();
        assertThat(report.getRecommendation()).isNotNull();
        assertThat(report.getMermaidDiagram()).isNotNull();
    }

    @Test
    void generateReportWithScoresPopulatesAllSections() {
        Map<String, Integer> scores = Map.of("CP-1010", 90, "BP-1010", 80);
        ArchitectureReport report = reportService.generateReport(scores, "secure voice communications", 50);

        assertThat(report.getBusinessText()).isEqualTo("secure voice communications");
        assertThat(report.getScores()).isEqualTo(scores);
        assertThat(report.getArchitectureView()).isNotNull();
        assertThat(report.getGapAnalysis()).isNotNull();
        assertThat(report.getPatternDetection()).isNotNull();
        assertThat(report.getRecommendation()).isNotNull();
        assertThat(report.getMermaidDiagram()).isNotNull();
    }

    @Test
    void generateReportWithNullScoresDoesNotThrow() {
        ArchitectureReport report = reportService.generateReport(null, "test", 0);

        assertThat(report).isNotNull();
        assertThat(report.getScores()).isEmpty();
    }

    @Test
    void renderMarkdownContainsExpectedSections() {
        Map<String, Integer> scores = Map.of("CP-1010", 90);
        ArchitectureReport report = reportService.generateReport(scores, "test requirement", 50);
        String markdown = reportService.renderMarkdown(report);

        assertThat(markdown).contains("# Architecture Analysis Report");
        assertThat(markdown).contains("## 1. Architecture Summary");
        assertThat(markdown).contains("## 2. Gap Analysis");
        assertThat(markdown).contains("## 3. Detected Patterns");
        assertThat(markdown).contains("## 4. Recommendations");
        assertThat(markdown).contains("Generated by Taxonomy Architecture Analyzer");
    }

    @Test
    void renderMarkdownIncludesBusinessText() {
        ArchitectureReport report = reportService.generateReport(
                Map.of("CP-1010", 90), "my special requirement", 50);
        String markdown = reportService.renderMarkdown(report);

        assertThat(markdown).contains("my special requirement");
    }

    @Test
    void renderMarkdownIncludesMermaidDiagram() {
        ArchitectureReport report = reportService.generateReport(
                Map.of("CP-1010", 90), "test", 50);
        String markdown = reportService.renderMarkdown(report);

        assertThat(markdown).contains("```mermaid");
    }

    @Test
    void renderHtmlContainsHtmlStructure() {
        ArchitectureReport report = reportService.generateReport(
                Map.of("CP-1010", 90), "test", 50);
        String html = reportService.renderHtml(report);

        assertThat(html).contains("<!DOCTYPE html>");
        assertThat(html).contains("<html");
        assertThat(html).contains("Architecture Analysis Report");
        assertThat(html).contains("</html>");
    }

    @Test
    void renderDocxProducesNonEmptyBytes() {
        ArchitectureReport report = reportService.generateReport(
                Map.of("CP-1010", 90), "test requirement", 50);
        byte[] docx = reportService.renderDocx(report);

        assertThat(docx).isNotNull();
        assertThat(docx.length).isGreaterThan(0);
        // DOCX files start with PK (ZIP magic bytes)
        assertThat(docx[0]).isEqualTo((byte) 0x50);
        assertThat(docx[1]).isEqualTo((byte) 0x4B);
    }

    @Test
    void renderHtmlConvertsHeadingsCorrectly() {
        ArchitectureReport report = reportService.generateReport(
                Map.of("CP-1010", 90), "test", 50);
        String html = reportService.renderHtml(report);

        assertThat(html).contains("<h1>");
        assertThat(html).contains("<h2>");
    }

    @Test
    void renderHtmlConvertsTablesCorrectly() {
        ArchitectureReport report = reportService.generateReport(
                Map.of("CP-1010", 90), "test", 50);
        String html = reportService.renderHtml(report);

        assertThat(html).contains("<table>");
        assertThat(html).contains("<th>");
    }

    @Test
    void renderHtmlConvertsBoldAndCode() {
        ArchitectureReport report = reportService.generateReport(
                Map.of("CP-1010", 90), "test", 50);
        String html = reportService.renderHtml(report);

        assertThat(html).contains("<strong>");
        assertThat(html).contains("<code>");
    }

    // ── Report API Endpoint Tests ─────────────────────────────────────────────

    @Test
    void markdownEndpointReturnsOk() throws Exception {
        mockMvc.perform(post("/api/report/markdown")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{\"CP-1010\":90},\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isOk())
                .andExpect(header().string("Content-Disposition", "attachment; filename=\"architecture-report.md\""));
    }

    @Test
    void htmlEndpointReturnsOk() throws Exception {
        mockMvc.perform(post("/api/report/html")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{\"CP-1010\":90},\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isOk())
                .andExpect(header().string("Content-Disposition", "attachment; filename=\"architecture-report.html\""));
    }

    @Test
    void docxEndpointReturnsOk() throws Exception {
        mockMvc.perform(post("/api/report/docx")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{\"CP-1010\":90},\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isOk())
                .andExpect(header().string("Content-Disposition", "attachment; filename=\"architecture-report.docx\""));
    }

    @Test
    void jsonEndpointReturnsOk() throws Exception {
        mockMvc.perform(post("/api/report/json")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{\"CP-1010\":90},\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.businessText").value("test"))
                .andExpect(jsonPath("$.architectureView").isMap())
                .andExpect(jsonPath("$.gapAnalysis").isMap())
                .andExpect(jsonPath("$.patternDetection").isMap())
                .andExpect(jsonPath("$.recommendation").isMap())
                .andExpect(jsonPath("$.mermaidDiagram").isString());
    }

    @Test
    void reportEndpointRejectsMissingScores() throws Exception {
        mockMvc.perform(post("/api/report/markdown")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":null,\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isBadRequest());
    }

    @Test
    void reportEndpointRejectsEmptyScores() throws Exception {
        mockMvc.perform(post("/api/report/markdown")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{},\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isBadRequest());
    }

    // ── ExplanationTrace Service Tests ────────────────────────────────────────

    @Test
    void buildTraceForExistingNodeReturnsTrace() {
        Map<String, Integer> scores = Map.of("CP-1010", 85);
        ExplanationTrace trace = traceService.buildTrace("CP-1010", scores, Map.of(), "test requirement");

        assertThat(trace).isNotNull();
        assertThat(trace.getSemanticScore()).isGreaterThan(0);
        assertThat(trace.getTaxonomyRoot()).isNotNull();
        assertThat(trace.getSummaryText()).isNotNull();
        assertThat(trace.getScoreBreakdown()).isNotEmpty();
        assertThat(trace.getRelationPath()).isNotEmpty();
    }

    @Test
    void buildTraceForUnknownNodeReturnsSummary() {
        ExplanationTrace trace = traceService.buildTrace("UNKNOWN-999", Map.of(), Map.of(), "test");

        assertThat(trace.getSummaryText()).contains("Node not found");
    }

    @Test
    void buildTracesForMultipleNodesReturnsMap() {
        Map<String, Integer> scores = Map.of("CP-1010", 90, "BP-1010", 80);
        Map<String, ExplanationTrace> traces = traceService.buildTraces(scores, Map.of(), "test", 50);

        assertThat(traces).isNotEmpty();
        assertThat(traces).containsKey("CP-1010");
        assertThat(traces).containsKey("BP-1010");
    }

    @Test
    void buildTracesWithEmptyScoresReturnsEmpty() {
        Map<String, ExplanationTrace> traces = traceService.buildTraces(Map.of(), Map.of(), "test", 50);

        assertThat(traces).isEmpty();
    }

    @Test
    void buildTraceExtractsMatchedKeywords() {
        Map<String, Integer> scores = Map.of("CP-1010", 85);
        ExplanationTrace trace = traceService.buildTrace("CP-1010", scores, Map.of(),
                "communications secure voice capability");

        assertThat(trace.getMatchedKeywords()).isNotNull();
        // Keywords are lowercase tokens from business text matching node name tokens
    }

    @Test
    void scoreBreakdownContainsExpectedComponents() {
        Map<String, Integer> scores = Map.of("CP-1010", 90);
        ExplanationTrace trace = traceService.buildTrace("CP-1010", scores, Map.of(), "test");

        assertThat(trace.getScoreBreakdown()).isNotEmpty();
        assertThat(trace.getScoreBreakdown().stream()
                .map(ExplanationTrace.ScoreComponent::getFactor))
                .contains("Direct LLM Score", "Keyword Overlap", "Hierarchy Depth");
    }

    // ── ExplanationTrace API Endpoint Tests ───────────────────────────────────

    @Test
    void explainNodeEndpointReturnsOk() throws Exception {
        mockMvc.perform(post("/api/explain/CP-1010")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{\"CP-1010\":90},\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.semanticScore").isNumber())
                .andExpect(jsonPath("$.scoreBreakdown").isArray())
                .andExpect(jsonPath("$.relationPath").isArray())
                .andExpect(jsonPath("$.summaryText").isString());
    }

    @Test
    void explainAllEndpointReturnsOk() throws Exception {
        mockMvc.perform(post("/api/explain")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{\"CP-1010\":90,\"BP-1010\":80},\"businessText\":\"test\",\"minScore\":50}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.CP-1010").isMap())
                .andExpect(jsonPath("$.BP-1010").isMap());
    }

    @Test
    void explainNodeReturnsTraceWithBreakdown() throws Exception {
        mockMvc.perform(post("/api/explain/CP-1010")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"scores\":{\"CP-1010\":85},\"businessText\":\"capability test\",\"minScore\":50}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.scoreBreakdown[0].factor").value("Direct LLM Score"))
                .andExpect(jsonPath("$.scoreBreakdown[0].value").value(0.85));
    }

    // ── RecommendedElement ExplanationTrace Integration ───────────────────────

    @Test
    void recommendedElementHasExplanationTraceField() {
        RecommendedElement el = new RecommendedElement("CP-1010", "Test", "CP", 90, "reason");
        ExplanationTrace trace = new ExplanationTrace();
        trace.setSummaryText("test trace");
        el.setExplanationTrace(trace);

        assertThat(el.getExplanationTrace()).isNotNull();
        assertThat(el.getExplanationTrace().getSummaryText()).isEqualTo("test trace");
    }
}
