package com.taxonomy.architecture.decision;

import java.util.Locale;

/** Small bilingual label set shared by report renderers. */
public final class DecisionReportLabels {

    private final boolean german;

    public DecisionReportLabels(String languageTag) {
        String tag = languageTag == null ? "en" : languageTag;
        this.german = "de".equalsIgnoreCase(Locale.forLanguageTag(tag).getLanguage());
    }

    public boolean german() { return german; }

    public String subtitle() { return german ? "Nachvollziehbare KI-gestützte Zuordnung einer Anforderung zur Taxonomiehierarchie" : "Traceable AI-assisted mapping of a requirement to the taxonomy hierarchy"; }
    public String documentStatus() { return german ? "Dokumentstatus" : "Document status"; }
    public String finalStatus() { return german ? "Abschließend" : "Final"; }
    public String finalWarnings() { return german ? "Abschließend mit Hinweisen" : "Final with warnings"; }
    public String draft() { return german ? "Entwurf – Analyse unvollständig" : "Draft – analysis incomplete"; }
    public String noResult() { return german ? "Kein Blattknoten ermittelt" : "No leaf identified"; }
    public String requirement() { return german ? "Zugrunde liegende Anforderung" : "Underlying requirement"; }
    public String taxonomyBasis() { return german ? "Grundlage der Taxonomiedaten" : "Taxonomy data basis"; }
    public String catalogue() { return german ? "Katalog" : "Catalogue"; }
    public String dataVersion() { return german ? "Deklarierte Datenversion" : "Declared data version"; }
    public String sourceFile() { return german ? "Quelldatei" : "Source file"; }
    public String sourceDigest() { return german ? "SHA-256 der Quelldatei" : "Source file SHA-256"; }
    public String dataDigest() { return german ? "SHA-256 des geladenen Datenbestands" : "Loaded data SHA-256"; }
    public String analysisDigest() { return german ? "SHA-256 des Analysesnapshots" : "Analysis snapshot SHA-256"; }
    public String nodes() { return german ? "Knoten / Wurzelbereiche" : "Nodes / root areas"; }
    public String provenance() { return german ? "Erzeugung und Versionsnachweis" : "Generation and version evidence"; }
    public String generatedAt() { return german ? "Erzeugt am" : "Generated at"; }
    public String generatedBy() { return german ? "Erzeugt durch Account" : "Generated by account"; }
    public String applicationVersion() { return german ? "Taxonomy-Anwendungsversion" : "Taxonomy application version"; }
    public String buildCommit() { return german ? "Anwendungs-Build-Commit" : "Application build commit"; }
    public String repository() { return german ? "Repository" : "Repository"; }
    public String workspace() { return german ? "Workspace" : "Workspace"; }
    public String branch() { return german ? "Branch" : "Branch"; }
    public String basedOnCommit() { return german ? "Datenstand / Commit" : "Data state / commit"; }
    public String analysisProvider() { return german ? "KI-Anbieter" : "AI provider"; }
    public String analysisStatus() { return german ? "Analysestatus" : "Analysis status"; }
    public String analysisModel() { return german ? "KI-Modell" : "AI model"; }
    public String analysisSnapshot() { return german ? "Unveränderlicher Analysesnapshot" : "Immutable analysis snapshot"; }
    public String requirementVersion() { return german ? "Anforderungsversion" : "Requirement version"; }
    public String analysisCreatedAt() { return german ? "Analyse erstellt am" : "Analysis created at"; }
    public String analysisCreatedBy() { return german ? "Analyse erstellt durch" : "Analysis created by"; }
    public String recordedTaxonomyDigest() { return german ? "Im Snapshot gespeicherter Taxonomie-Fingerabdruck" : "Taxonomy fingerprint recorded in snapshot"; }
    public String promptDigest() { return german ? "Prompt-Fingerabdruck" : "Prompt fingerprint"; }
    public String hierarchyEvidence() { return german ? "Hierarchiequelle" : "Hierarchy evidence"; }
    public String frozenHierarchy() { return german ? "Im Analysesnapshot eingefrorene Taxonomiehierarchie" : "Taxonomy hierarchy frozen in the analysis snapshot"; }
    public String liveHierarchy() { return german ? "Aktuell geladene Taxonomiehierarchie" : "Currently loaded taxonomy hierarchy"; }
    public String completeness() { return german ? "Vollständigkeit" : "Completeness"; }
    public String executiveSummary() { return german ? "Kurzfassung" : "Executive summary"; }
    public String leadingLeaf() { return german ? "Führender Blattknoten nach effektiver Relevanz" : "Leading leaf by effective relevance"; }
    public String highestPath() { return german ? "Führender Entscheidungspfad" : "Leading decision path"; }
    public String step() { return german ? "Schritt" : "Step"; }
    public String node() { return german ? "Knoten" : "Node"; }
    public String score() { return german ? "Effektive Relevanz" : "Effective relevance"; }
    public String localShare() { return german ? "Lokaler Anteil / Produkteignung" : "Local share / product suitability"; }
    public String rationale() { return german ? "Kurzbegründung" : "Short rationale"; }
    public String reasonSource() { return german ? "Herkunft" : "Source"; }
    public String methodology() { return german ? "Methodischer Hinweis" : "Methodology note"; }
    public String decisionChapters() { return german ? "Einzelentscheidungen entlang der Hierarchie" : "Individual hierarchy decisions"; }
    public String chapter() { return german ? "Entscheidung" : "Decision"; }
    public String parentNode() { return german ? "Vaterknoten" : "Parent node"; }
    public String parentScore() { return german ? "Wert des Vaterknotens" : "Parent score"; }
    public String decisionResult() { return german ? "Entscheidungsergebnis" : "Decision result"; }
    public String comparison() { return german ? "Vergleichende Begründung" : "Comparative rationale"; }
    public String alternatives() { return german ? "Direkte Kindknoten und Alternativen" : "Direct children and alternatives"; }
    public String rank() { return german ? "Rang" : "Rank"; }
    public String disposition() { return german ? "Folge" : "Disposition"; }
    public String leadingSibling() { return german ? "Führend" : "Leading"; }
    public String continued() { return german ? "Pfad fortgeführt" : "Path continued"; }
    public String leafCandidate() { return german ? "Blattkandidat" : "Leaf candidate"; }
    public String rejected() { return german ? "0 % – nicht fortgeführt" : "0% – not continued"; }
    public String notEvaluated() { return german ? "Nicht bewertet" : "Not evaluated"; }
    public String aiReason() { return german ? "Ursprüngliche KI-Begründung" : "Original AI reason"; }
    public String deterministicReason() { return german ? "Deterministische Herleitung" : "Deterministic derivation"; }
    public String missingReason() { return german ? "Keine Begründung vorhanden" : "No reason available"; }
    public String warnings() { return german ? "Hinweise und Prüfvorbehalte" : "Warnings and review reservations"; }
    public String leadingLeaves() { return german ? "Rangliste nach effektiver Relevanz" : "Ranking by effective relevance"; }
    public String taxonomyRoot() { return german ? "Taxonomiebereich" : "Taxonomy root"; }
    public String hierarchyPath() { return german ? "Hierarchiepfad" : "Hierarchy path"; }
    public String appendix() { return german ? "Nachweis und Methodik" : "Evidence and methodology"; }
    public String page() { return german ? "Seite" : "Page"; }
    public String panel() { return german ? "Teil" : "Panel"; }
    public String depth() { return german ? "Tiefe" : "Depth"; }
    public String of() { return german ? "von" : "of"; }
    public String continuedLabel() { return german ? "FORTGEFÜHRT" : "CONTINUED"; }
    public String leafLabel() { return german ? "BLATT" : "LEAF"; }
    public String rejectedLabel() { return german ? "0 %" : "0%"; }
    public String notEvaluatedLabel() { return german ? "NICHT BEWERTET" : "NOT EVALUATED"; }
    public String leadingLabel() { return german ? "FÜHREND" : "LEADING"; }
    public String generatedNotice() { return german ? "Erzeugt durch Taxonomy Architecture Analyzer" : "Generated by Taxonomy Architecture Analyzer"; }
    public String architectureTitle() { return german ? "Architekturbericht" : "Architecture report"; }
    public String contents() { return german ? "Inhalt und Navigation" : "Contents and navigation"; }
    public String treeOverview() { return german ? "Vollständiger Entscheidungsbaum" : "Complete decision tree"; }
    public String scope() { return german ? "Geltungsbereich" : "Scope"; }
    public String recommendation() { return german ? "Empfehlung aus gespeicherter Evidenz" : "Recommendation from saved evidence"; }
    public String gaps() { return german ? "Offene Lücken und Vorbehalte" : "Unresolved gaps and reservations"; }
    public String architectureOverview() { return german ? "Architekturübersicht" : "Architecture overview"; }
    public String architectureDetail() { return german ? "Architekturdetail" : "Architecture detail"; }
    public String elements() { return german ? "Elementinventar" : "Element inventory"; }
    public String relations() { return german ? "Beziehungsinventar" : "Relation inventory"; }
    public String relationKeyNotice() { return german ? "Kompakte Beziehungskennungen erscheinen nur bei ausreichendem Platz. Die zugehörigen Beziehungsschlüssel und das vollständige Inventar enthalten jede Kennung, Quelle, jedes Ziel und jeden Typ." : "Compact relation IDs appear where space permits. The associated relation keys and complete inventory identify every relation by ID, source, target and type."; }
    public String legend() { return german ? "Legende" : "Legend"; }
    public String anchor() { return german ? "Anforderungsanker" : "Requirement anchor"; }
    public String directedRelation() { return german ? "Gerichtete Beziehung; Pfeil zeigt zum Ziel" : "Directed relation; arrow points to target"; }
    public String container() { return german ? "Visueller Container" : "Visual container"; }
    public String figure() { return german ? "Abbildung" : "Figure"; }
    public String table() { return german ? "Tabelle" : "Table"; }
    public String source() { return german ? "Quelle" : "Source"; }
    public String target() { return german ? "Ziel" : "Target"; }
    public String type() { return german ? "Typ" : "Type"; }
    public String category() { return german ? "Kategorie" : "Category"; }
    public String identifier() { return german ? "Kennung" : "Identifier"; }
    public String titleLabel() { return german ? "Titel" : "Title"; }
    public String graphDigest() { return german ? "SHA-256 des Architekturgraphen" : "Architecture graph SHA-256"; }
    public String unknown() { return german ? "Unbekannt" : "Unknown"; }
    public String noneRecorded() { return german ? "Keine im Snapshot dokumentiert" : "None recorded in snapshot"; }
    public String frozenScope() { return german ? "Gespeicherte Architektur und Entscheidungsevidenz der ausgewählten Anforderungsversion." : "Saved architecture and decision evidence for the selected requirement version."; }
    public String overviewPurpose() { return german ? "Gesamtübersicht zur Orientierung; lesbare Details folgen." : "Whole-graph orientation view; reading-scale details follow."; }
    public String detailPurpose() { return german ? "Detailansicht; Randknoten können in weiteren Ansichten wiederholt werden." : "Detail view; boundary nodes may repeat in other panels."; }
    public String includedNodes() { return german ? "Enthaltene Knoten" : "Included nodes"; }
    public String relationTypes() { return german ? "Beziehungstypen" : "Relation types"; }
    public String orphanWarning() { return german ? "Verwaiste Entscheidungskomponente ohne dokumentierten Vater" : "Orphan decision component without a recorded parent"; }
    public String openChapter() { return german ? "Kapitel öffnen" : "Open chapter"; }
    public String project() { return german ? "Projekt" : "Project"; }
    public String requirementId() { return german ? "Anforderungskennung" : "Requirement ID"; }
    public String evidenceEyebrow() { return german ? "TAXONOMY · ENTSCHEIDUNGSNACHWEIS" : "TAXONOMY · DECISION EVIDENCE"; }
}
