package com.taxonomy.dsl.storage;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.carstenartur.jgit.storage.hibernate.schema.CoreSchemaMigrations;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

/** Verifies the real pre-library Taxonomy adoption path against PostgreSQL. */
@Testcontainers
@Tag("db-postgres")
class JgitStoragePostgresMigrationIT {

    @Container
    @SuppressWarnings("rawtypes")
    static PostgreSQLContainer database = new PostgreSQLContainer("postgres:16-alpine")
            .withDatabaseName("taxonomy")
            .withUsername("taxonomy")
            .withPassword("taxonomy");

    @Test
    void adoptsActualTaxonomySchemaThroughReleasedV1AndV2WithoutRewritingData()
            throws Exception {
        DataSource dataSource = dataSource();
        installLegacySchema(dataSource);
        byte[] packData = new byte[] {9, 8, 7, 6, 5};
        String refName = "refs/heads/" + "p".repeat(200);
        insertLegacyPack(dataSource, "legacy", "pack-a", "reftable", packData);
        insertLegacyReflog(dataSource, refName);

        JgitStorageSchemaMigrationConfig.migrateCoreSchema(flyway(dataSource), true);

        assertEquals(32, columnSize(dataSource, "git_packs", "pack_extension"));
        assertTrue(columnSize(dataSource, "git_reflog", "ref_name") >= 1024);
        assertArrayEquals(packData, storedPackData(dataSource));
        assertEquals(refName, storedRefName(dataSource));
        assertCommitted(dataSource);
        assertEquals(
                List.of("0", "1", "2"),
                successfulVersions(
                        dataSource,
                        CoreSchemaMigrations.LEGACY_ADOPTION_SCHEMA_HISTORY_TABLE));
        assertEquals(
                List.of(CoreSchemaMigrations.CURRENT_SCHEMA_VERSION),
                successfulVersions(dataSource, CoreSchemaMigrations.SCHEMA_HISTORY_TABLE));

        SQLException duplicate = assertThrows(
                SQLException.class,
                () -> insertLegacyPack(
                        dataSource, "legacy", "pack-a", "reftable", packData));
        assertEquals("23505", duplicate.getSQLState());
    }

    private static DataSource dataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.postgresql.Driver");
        dataSource.setUrl(database.getJdbcUrl());
        dataSource.setUsername(database.getUsername());
        dataSource.setPassword(database.getPassword());
        return dataSource;
    }

    private static Flyway flyway(DataSource dataSource) {
        return Flyway.configure()
                .dataSource(dataSource)
                .locations(CoreSchemaMigrations.POSTGRESQL_LOCATION)
                .table(CoreSchemaMigrations.SCHEMA_HISTORY_TABLE)
                .load();
    }

    private static void installLegacySchema(DataSource dataSource) throws SQLException {
        execute(dataSource, """
                create table git_packs (
                    id bigint generated by default as identity not null,
                    repository_name varchar(255) not null,
                    pack_name varchar(255) not null,
                    pack_extension varchar(255) not null,
                    data bytea not null,
                    file_size bigint not null,
                    created_at timestamp(6) with time zone not null,
                    primary key (id)
                )
                """);
        execute(dataSource, "create index idx_pack_repo on git_packs (repository_name)");
        execute(dataSource,
                "create index idx_pack_repo_name on git_packs (repository_name, pack_name)");
        execute(dataSource, """
                create table git_reflog (
                    id bigint generated by default as identity not null,
                    version bigint,
                    repository_name varchar(255) not null,
                    ref_name varchar(255) not null,
                    old_id varchar(40),
                    new_id varchar(40),
                    who_name varchar(255),
                    who_email varchar(255),
                    who_when timestamp(6) with time zone not null,
                    message varchar(2048),
                    primary key (id)
                )
                """);
        execute(dataSource, "create index idx_reflog_repo on git_reflog (repository_name)");
        execute(dataSource,
                "create index idx_reflog_repo_ref on git_reflog (repository_name, ref_name)");
    }

    private static void insertLegacyPack(
            DataSource dataSource,
            String repositoryName,
            String packName,
            String extension,
            byte[] data) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             var statement = connection.prepareStatement("""
                     insert into git_packs
                         (repository_name, pack_name, pack_extension, data, file_size, created_at)
                     values (?, ?, ?, ?, ?, ?)
                     """)) {
            statement.setString(1, repositoryName);
            statement.setString(2, packName);
            statement.setString(3, extension);
            statement.setBytes(4, data);
            statement.setLong(5, data.length);
            statement.setTimestamp(6, Timestamp.from(Instant.now()));
            statement.executeUpdate();
        }
    }

    private static void insertLegacyReflog(DataSource dataSource, String refName)
            throws SQLException {
        try (Connection connection = dataSource.getConnection();
             var statement = connection.prepareStatement("""
                     insert into git_reflog
                         (version, repository_name, ref_name, old_id, new_id,
                          who_name, who_email, who_when, message)
                     values (?, ?, ?, ?, ?, ?, ?, ?, ?)
                     """)) {
            statement.setLong(1, 0);
            statement.setString(2, "legacy");
            statement.setString(3, refName);
            statement.setString(4, null);
            statement.setString(5, "0123456789012345678901234567890123456789");
            statement.setString(6, "Migration Test");
            statement.setString(7, "migration@example.invalid");
            statement.setTimestamp(8, Timestamp.from(Instant.now()));
            statement.setString(9, "commit: preserve PostgreSQL reflog");
            statement.executeUpdate();
        }
    }

    private static byte[] storedPackData(DataSource dataSource) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("select data from git_packs")) {
            assertTrue(resultSet.next());
            return resultSet.getBytes(1);
        }
    }

    private static String storedRefName(DataSource dataSource) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("select ref_name from git_reflog")) {
            assertTrue(resultSet.next());
            return resultSet.getString(1);
        }
    }

    private static void assertCommitted(DataSource dataSource) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(
                     "select committed, committed_at from git_packs")) {
            assertTrue(resultSet.next());
            assertTrue(resultSet.getBoolean(1));
            assertNotNull(resultSet.getTimestamp(2));
        }
    }

    private static List<String> successfulVersions(
            DataSource dataSource, String historyTable) throws SQLException {
        List<String> versions = new ArrayList<>();
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(
                     "select version from " + historyTable
                             + " where success = true order by installed_rank")) {
            while (resultSet.next()) {
                versions.add(resultSet.getString(1));
            }
        }
        return versions;
    }

    private static int columnSize(
            DataSource dataSource, String tableName, String columnName) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metadata = connection.getMetaData();
            try (ResultSet resultSet = metadata.getColumns(
                    null, connection.getSchema(), tableName, "%")) {
                while (resultSet.next()) {
                    if (columnName.equalsIgnoreCase(resultSet.getString("COLUMN_NAME"))) {
                        return resultSet.getInt("COLUMN_SIZE");
                    }
                }
            }
        }
        throw new AssertionError("Missing column " + tableName + "." + columnName);
    }

    private static void execute(DataSource dataSource, String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
