package com.taxonomy.dsl.storage;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.carstenartur.jgit.storage.hibernate.schema.CoreSchemaMigrations;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.UUID;

import javax.sql.DataSource;

import org.flywaydb.core.Flyway;
import org.hsqldb.jdbc.JDBCDataSource;
import org.junit.jupiter.api.Test;

class JgitStorageSchemaIndexValidationTest {

    @Test
    void rejectsUnversionedCurrentSchemaWithoutUniquePackIdentity() throws Exception {
        DataSource dataSource = dataSource("missing-current-unique");
        flyway(dataSource).migrate();
        execute(dataSource, "drop table " + CoreSchemaMigrations.SCHEMA_HISTORY_TABLE);
        execute(dataSource,
                "alter table git_packs drop constraint uk_pack_repo_name_ext");

        IllegalStateException error = assertThrows(
                IllegalStateException.class,
                () -> JgitStorageSchemaMigrationConfig.migrateCoreSchema(
                        flyway(dataSource), false));

        assertTrue(error.getMessage().contains("unique index"));
        assertFalse(tableExists(dataSource, CoreSchemaMigrations.SCHEMA_HISTORY_TABLE));
    }

    @Test
    void rejectsLegacySchemaWithoutRequiredIndexesBeforeDdl() throws Exception {
        DataSource dataSource = dataSource("missing-legacy-indexes");
        installLegacyTablesWithoutIndexes(dataSource);

        IllegalStateException error = assertThrows(
                IllegalStateException.class,
                () -> JgitStorageSchemaMigrationConfig.migrateCoreSchema(
                        flyway(dataSource), true));

        assertTrue(error.getMessage().contains("missing the required index"));
        assertFalse(columnExists(dataSource, "git_packs", "committed"));
        assertFalse(tableExists(
                dataSource,
                CoreSchemaMigrations.LEGACY_ADOPTION_SCHEMA_HISTORY_TABLE));
    }

    private static DataSource dataSource(String purpose) {
        JDBCDataSource dataSource = new JDBCDataSource();
        String databaseName = purpose + "_" + UUID.randomUUID().toString().replace("-", "");
        dataSource.setUrl("jdbc:hsqldb:mem:" + databaseName + ";DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    private static Flyway flyway(DataSource dataSource) {
        return Flyway.configure()
                .dataSource(dataSource)
                .locations(CoreSchemaMigrations.HSQLDB_LOCATION)
                .table(CoreSchemaMigrations.SCHEMA_HISTORY_TABLE)
                .load();
    }

    private static void installLegacyTablesWithoutIndexes(DataSource dataSource)
            throws SQLException {
        execute(dataSource, """
                create table git_packs (
                    id bigint generated by default as identity not null,
                    repository_name varchar(255) not null,
                    pack_name varchar(255) not null,
                    pack_extension varchar(255) not null,
                    data blob not null,
                    file_size bigint not null,
                    created_at timestamp(6) not null,
                    primary key (id)
                )
                """);
        execute(dataSource, """
                create table git_reflog (
                    id bigint generated by default as identity not null,
                    version bigint,
                    repository_name varchar(255) not null,
                    ref_name varchar(255) not null,
                    old_id varchar(40),
                    new_id varchar(40),
                    who_name varchar(255),
                    who_email varchar(255),
                    who_when timestamp(6) not null,
                    message varchar(2048),
                    primary key (id)
                )
                """);
    }

    private static boolean tableExists(DataSource dataSource, String tableName)
            throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metadata = connection.getMetaData();
            try (ResultSet resultSet = metadata.getTables(
                    null, connection.getSchema(), "%", new String[] {"TABLE"})) {
                while (resultSet.next()) {
                    if (tableName.equalsIgnoreCase(resultSet.getString("TABLE_NAME"))) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    private static boolean columnExists(
            DataSource dataSource, String tableName, String columnName) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metadata = connection.getMetaData();
            try (ResultSet resultSet = metadata.getColumns(
                    null,
                    connection.getSchema(),
                    tableName.toUpperCase(Locale.ROOT),
                    columnName.toUpperCase(Locale.ROOT))) {
                return resultSet.next();
            }
        }
    }

    private static void execute(DataSource dataSource, String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
