package com.taxonomy.security.persistence;

import com.taxonomy.security.config.PrincipalIdentityConfiguration;
import com.taxonomy.security.model.AppUser;
import com.taxonomy.security.service.PrincipalIdentityService;
import jakarta.persistence.EntityManagerFactory;
import org.hsqldb.jdbc.JDBCDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;

import javax.sql.DataSource;
import java.util.Map;
import java.util.UUID;
import static org.assertj.core.api.Assertions.*;

class PrincipalStartupMigrationTest {
    @Test void upgradesLegacyAccountsBeforeHibernateValidationAndSupportsNewAccounts() {
        try (var context = new AnnotationConfigApplicationContext(Persistence.class)) {
            var identities = context.getBean(PrincipalIdentityService.class);
            assertThat(identities.local(1L).scopeKey()).isEqualTo("legacy");
            var entityManager = context.getBean(EntityManagerFactory.class).createEntityManager();
            try {
                entityManager.getTransaction().begin();
                var user = new AppUser(); user.setUsername("new-account"); user.setPasswordHash("unused-hash");
                entityManager.persist(user); entityManager.getTransaction().commit();
                assertThat(identities.local(user.getId()).id().value().toString()).isEqualTo(user.getPrincipalId());
            } finally { entityManager.close(); }
        }
    }

    @Configuration(proxyBeanMethods = false)
    @Import(PrincipalIdentityConfiguration.class)
    static class Persistence {
        @Bean DataSource dataSource() {
            var database = new JDBCDataSource();
            database.setUrl("jdbc:hsqldb:mem:startup-" + UUID.randomUUID()); database.setUser("sa");
            var jdbc = new JdbcTemplate(database);
            jdbc.execute("create table app_user(id bigint generated by default as identity(start with 2) primary key, username varchar(255) unique, password_hash varchar(255), enabled boolean, must_change_password boolean, display_name varchar(255), email varchar(255))");
            jdbc.execute("create table app_role(id bigint generated by default as identity primary key, name varchar(255))");
            jdbc.execute("create table user_roles(user_id bigint, role_id bigint)");
            jdbc.update("insert into app_user(id, username, password_hash, enabled, must_change_password) values (1, 'legacy', 'unused-hash', true, false)");
            return database;
        }

        @Bean LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource database) {
            var factory = new LocalContainerEntityManagerFactoryBean();
            factory.setDataSource(database); factory.setPackagesToScan("com.taxonomy.security.model");
            factory.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
            factory.setJpaPropertyMap(Map.of("hibernate.hbm2ddl.auto", "validate"));
            return factory;
        }
    }
}
