create table if not exists analysis_working_draft (
    id bigint generated by default as identity primary key,
    scope_key varchar(1024) not null,
    workspace_id varchar(320) not null,
    username varchar(160) not null,
    payload_json text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null default 0,
    constraint uq_analysis_draft_scope_user unique (scope_key, username)
);

create index if not exists idx_analysis_draft_workspace_user
    on analysis_working_draft (workspace_id, username);

create index if not exists idx_analysis_draft_scope
    on analysis_working_draft (scope_key);
