-- Taxonomy application schema baseline for a fresh PostgreSQL installation.
-- JGit Core tables and their history remain owned by the separate released migration stream.

create table app_role (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique
);
create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password_hash varchar(255) not null,
    enabled boolean not null,
    must_change_password boolean not null,
    display_name varchar(255),
    email varchar(255)
);
create table architecture_commit_index (
    id bigint generated by default as identity primary key,
    commit_id varchar(40) not null,
    author varchar(255),
    commit_timestamp timestamp(6) with time zone not null,
    message varchar(500),
    changed_files varchar(2000),
    tokenized_change_text varchar(10000),
    affected_element_ids varchar(2000),
    affected_relation_ids varchar(2000),
    branch varchar(255),
    indexed_at timestamp(6) with time zone not null,
    unique (commit_id)
);
create table architecture_dsl_document (
    id bigint generated by default as identity primary key,
    path varchar(255) not null,
    commit_id varchar(255),
    branch varchar(255),
    namespace varchar(255),
    dsl_version varchar(255),
    raw_content oid not null,
    parsed_at timestamp(6) with time zone not null
);
create table context_history_record (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    from_context_id varchar(255),
    to_context_id varchar(255),
    from_branch varchar(255),
    to_branch varchar(255),
    from_commit_id varchar(255),
    to_commit_id varchar(255),
    reason varchar(255),
    origin_context_id varchar(255),
    created_at timestamp(6) with time zone not null
);
create index idx_history_username on context_history_record (username);
create index idx_history_created on context_history_record (created_at);
create table requirement_coverage (
    id bigint generated by default as identity primary key,
    requirement_id varchar(255) not null,
    requirement_text varchar(2000),
    node_code varchar(255) not null,
    score integer not null,
    analyzed_at timestamp(6) with time zone,
    unique (requirement_id, node_code)
);
create table source_artifact (
    id bigint generated by default as identity primary key,
    source_type varchar(255) not null,
    title varchar(500) not null,
    canonical_identifier varchar(500),
    canonical_url varchar(1000),
    origin_system varchar(200),
    author varchar(200),
    description varchar(2000),
    language varchar(10),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone
);
create table source_version (
    id bigint generated by default as identity primary key,
    source_artifact_id bigint not null,
    version_label varchar(200),
    retrieved_at timestamp(6) with time zone not null,
    effective_date date,
    content_hash varchar(128),
    mime_type varchar(100),
    storage_location varchar(1000),
    raw_text_location varchar(1000),
    foreign key (source_artifact_id) references source_artifact (id)
);
create table source_fragment (
    id bigint generated by default as identity primary key,
    source_version_id bigint not null,
    section_path varchar(500),
    paragraph_ref varchar(100),
    page_from integer,
    page_to integer,
    fragment_text varchar(4000),
    fragment_hash varchar(128),
    parent_fragment_id bigint,
    chunk_level integer,
    foreign key (source_version_id) references source_version (id)
);
create table requirement_source_link (
    id bigint generated by default as identity primary key,
    requirement_id varchar(255) not null,
    source_artifact_id bigint not null,
    source_version_id bigint,
    source_fragment_id bigint,
    link_type varchar(255) not null,
    confidence float(53),
    note varchar(1000),
    foreign key (source_artifact_id) references source_artifact (id),
    foreign key (source_version_id) references source_version (id),
    foreign key (source_fragment_id) references source_fragment (id)
);
create table system_repository (
    id bigint generated by default as identity primary key,
    repository_id varchar(255) not null unique,
    display_name varchar(255),
    topology_mode varchar(255) not null,
    default_branch varchar(255) not null,
    external_url varchar(255),
    external_auth_token varchar(255),
    last_fetch_at timestamp(6) with time zone,
    last_push_at timestamp(6) with time zone,
    last_fetch_commit varchar(255),
    primary_repo boolean not null,
    created_at timestamp(6) with time zone not null
);
create table user_workspace (
    id bigint generated by default as identity primary key,
    workspace_id varchar(255) not null unique,
    username varchar(255) not null,
    display_name varchar(255),
    current_branch varchar(255) not null,
    base_branch varchar(255),
    shared boolean not null,
    created_at timestamp(6) with time zone not null,
    last_accessed_at timestamp(6) with time zone,
    provisioning_status varchar(255) not null,
    topology_mode varchar(255) not null,
    source_repository_id varchar(255),
    base_commit varchar(255),
    current_commit varchar(255),
    sync_target_branch varchar(255),
    provisioned_at timestamp(6) with time zone,
    provisioning_error varchar(255),
    description varchar(500),
    archived boolean not null,
    is_default boolean not null,
    constraint uq_workspace_user_name unique (username, display_name)
);
create index idx_workspace_username on user_workspace (username);
create index idx_workspace_shared on user_workspace (shared);
create table workspace_projection (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    workspace_id varchar(255) not null,
    projection_commit_id varchar(255),
    projection_branch varchar(255),
    projection_timestamp timestamp(6) with time zone,
    index_commit_id varchar(255),
    index_timestamp timestamp(6) with time zone,
    stale boolean not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    constraint uq_projection_username unique (username),
    constraint uq_projection_workspace unique (workspace_id)
);
create table sync_state (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    workspace_id varchar(255) not null,
    last_synced_commit_id varchar(255),
    last_sync_timestamp timestamp(6) with time zone,
    last_published_commit_id varchar(255),
    last_publish_timestamp timestamp(6) with time zone,
    sync_status varchar(255) not null,
    unpublished_commit_count integer not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    constraint uq_sync_username unique (username),
    constraint uq_sync_workspace unique (workspace_id)
);
create table taxonomy_node (
    id bigint generated by default as identity primary key,
    code varchar(255) not null unique,
    uuid varchar(255),
    name_en varchar(255) not null,
    name_de varchar(255),
    description_en oid,
    description_de oid,
    parent_code varchar(255),
    taxonomy_root varchar(255),
    node_level integer not null,
    dataset varchar(255),
    external_id varchar(255),
    source varchar(255),
    reference oid,
    sort_order integer,
    state varchar(255),
    semantic_embedding oid,
    has_embedding boolean not null,
    incoming_relation_count integer not null,
    outgoing_relation_count integer not null,
    requirement_coverage_count integer not null,
    graph_role varchar(255),
    parent_id bigint,
    foreign key (parent_id) references taxonomy_node (id)
);
create table taxonomy_relation (
    id bigint generated by default as identity primary key,
    source_node_id bigint not null,
    target_node_id bigint not null,
    relation_type varchar(255) not null,
    workspace_id varchar(255),
    workspace_scope_key varchar(255),
    owner_username varchar(255),
    description varchar(2000),
    provenance varchar(255),
    weight integer,
    bidirectional boolean not null,
    semantic_embedding oid,
    has_embedding boolean not null,
    constraint uk_taxonomy_relation_scope unique (source_node_id, target_node_id, relation_type, workspace_scope_key),
    foreign key (source_node_id) references taxonomy_node (id),
    foreign key (target_node_id) references taxonomy_node (id)
);
create index idx_rel_workspace on taxonomy_relation (workspace_id);
create index idx_rel_owner on taxonomy_relation (owner_username);
create table relation_proposal (
    id bigint generated by default as identity primary key,
    source_node_id bigint not null,
    target_node_id bigint not null,
    relation_type varchar(255) not null,
    status varchar(255) not null,
    confidence float(53) not null,
    rationale varchar(2000),
    provenance varchar(255),
    created_at timestamp(6) with time zone not null,
    reviewed_at timestamp(6) with time zone,
    workspace_id varchar(255),
    workspace_scope_key varchar(255),
    owner_username varchar(255),
    constraint uk_relation_proposal_scope unique (source_node_id, target_node_id, relation_type, workspace_scope_key),
    foreign key (source_node_id) references taxonomy_node (id),
    foreign key (target_node_id) references taxonomy_node (id)
);
create index idx_proposal_workspace on relation_proposal (workspace_id);
create index idx_proposal_owner on relation_proposal (owner_username);
create table relation_hypothesis (
    id bigint generated by default as identity primary key,
    source_node_id varchar(255) not null,
    target_node_id varchar(255) not null,
    relation_type varchar(255) not null,
    status varchar(255) not null,
    confidence float(53),
    analysis_session_id varchar(255),
    applied_in_current_analysis boolean not null,
    created_at timestamp(6) with time zone not null,
    workspace_id varchar(255),
    owner_username varchar(255),
    constraint uq_hypothesis_workspace_session_relation unique (workspace_id, source_node_id, target_node_id, relation_type, analysis_session_id)
);
create table relation_evidence (
    id bigint generated by default as identity primary key,
    hypothesis_id bigint not null,
    evidence_type varchar(255) not null,
    summary oid,
    full_text oid,
    confidence float(53),
    model_name varchar(255),
    model_version varchar(255),
    prompt_version varchar(255),
    input_snapshot oid,
    created_at timestamp(6) with time zone not null,
    foreign key (hypothesis_id) references relation_hypothesis (id)
);
create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    foreign key (user_id) references app_user (id),
    foreign key (role_id) references app_role (id)
);
