-- Project / requirement / solution / product portfolio schema.
-- CREATE IF NOT EXISTS supports safe adoption of installations that previously used Hibernate update.

create table if not exists arch_project (
    id bigint generated by default as identity primary key,
    scope_key varchar(160) not null,
    workspace_id varchar(120),
    owner_username varchar(160) not null,
    project_key varchar(64) not null,
    title varchar(240) not null,
    description varchar(4000),
    status varchar(32) not null,
    target_architecture varchar(4000),
    target_date date,
    budget_amount numeric(19,2),
    budget_currency varchar(3),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_proj_scope_key unique (scope_key, project_key)
);
create index if not exists idx_proj_scope on arch_project (scope_key);
create index if not exists idx_proj_status on arch_project (scope_key, status);

create table if not exists solution_definition (
    id bigint generated by default as identity primary key,
    scope_key varchar(160) not null,
    workspace_id varchar(120),
    solution_key varchar(64) not null,
    title varchar(240) not null,
    description varchar(4000),
    solution_type varchar(32) not null,
    operating_model varchar(32) not null,
    lifecycle_status varchar(32) not null,
    maturity_level integer not null,
    owner_username varchar(160) not null,
    responsible_organization varchar(240),
    cost_amount numeric(19,2),
    cost_currency varchar(3),
    risk_notes varchar(2000),
    lead_time_days integer,
    extension_attributes varchar(4000),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_sol_scope_key unique (scope_key, solution_key)
);
create index if not exists idx_sol_scope on solution_definition (scope_key);
create index if not exists idx_sol_lifecycle on solution_definition (scope_key, lifecycle_status);

create table if not exists product_catalog (
    id bigint generated by default as identity primary key,
    scope_key varchar(160) not null,
    workspace_id varchar(120),
    product_key varchar(64) not null,
    manufacturer varchar(240) not null,
    product_family varchar(240),
    product_name varchar(240) not null,
    edition_version varchar(160),
    product_status varchar(32) not null,
    end_of_support date,
    license_model varchar(500),
    operating_model varchar(32) not null,
    supported_platforms varchar(2000),
    security_features varchar(4000),
    compliance_features varchar(4000),
    cost_amount numeric(19,2),
    cost_currency varchar(3),
    cost_basis varchar(500),
    source_reference oid not null,
    verified_at timestamp(6) with time zone not null,
    created_by varchar(160) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_prod_scope_key unique (scope_key, product_key)
);
create index if not exists idx_prod_scope on product_catalog (scope_key);
create index if not exists idx_prod_status on product_catalog (scope_key, product_status);
create index if not exists idx_prod_eos on product_catalog (end_of_support);

create table if not exists project_requirement (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    requirement_key varchar(64) not null,
    title varchar(240) not null,
    status varchar(32) not null,
    priority integer not null,
    criticality varchar(32) not null,
    requirement_type varchar(32) not null,
    review_status varchar(32) not null,
    owner_username varchar(160) not null,
    current_version_id bigint,
    current_snapshot_id varchar(36),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_req_project_key unique (project_id, requirement_key),
    foreign key (project_id) references arch_project (id)
);
create index if not exists idx_req_project on project_requirement (project_id);
create index if not exists idx_req_status on project_requirement (project_id, status);

create table if not exists project_req_version (
    id bigint generated by default as identity primary key,
    requirement_id bigint not null,
    version_number integer not null,
    requirement_text oid not null,
    content_hash varchar(64) not null,
    change_reason varchar(1000),
    created_by varchar(160) not null,
    created_at timestamp(6) with time zone not null,
    source_artifact_id bigint,
    source_version_id bigint,
    source_fragment_ids oid,
    section_ref varchar(500),
    page_number integer,
    original_text oid,
    constraint uq_reqver_number unique (requirement_id, version_number),
    constraint uq_reqver_hash unique (requirement_id, content_hash),
    foreign key (requirement_id) references project_requirement (id)
);
create index if not exists idx_reqver_req on project_req_version (requirement_id);
create index if not exists idx_reqver_hash on project_req_version (requirement_id, content_hash);

create table if not exists req_analysis_job (
    id varchar(36) primary key,
    project_id bigint not null,
    status varchar(32) not null,
    idempotency_key varchar(160) not null,
    provider varchar(40),
    max_architecture_nodes integer not null,
    requested_by varchar(160) not null,
    workspace_id varchar(120),
    created_at timestamp(6) with time zone not null,
    started_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    total_items integer not null,
    successful_items integer not null,
    partial_items integer not null,
    failed_items integer not null,
    error_summary varchar(2000),
    row_version bigint not null,
    constraint uq_job_idempotency unique (project_id, idempotency_key),
    foreign key (project_id) references arch_project (id)
);
create index if not exists idx_job_project on req_analysis_job (project_id, created_at);
create index if not exists idx_job_status on req_analysis_job (project_id, status);

create table if not exists req_analysis_item (
    id bigint generated by default as identity primary key,
    job_id varchar(36) not null,
    requirement_id bigint not null,
    requirement_version_id bigint not null,
    status varchar(32) not null,
    snapshot_id varchar(36),
    attempt integer not null,
    started_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    error_message varchar(2000),
    row_version bigint not null,
    constraint uq_item_job_req unique (job_id, requirement_id),
    foreign key (job_id) references req_analysis_job (id),
    foreign key (requirement_id) references project_requirement (id),
    foreign key (requirement_version_id) references project_req_version (id)
);
create index if not exists idx_item_job on req_analysis_item (job_id);
create index if not exists idx_item_req on req_analysis_item (requirement_id);

create table if not exists req_analysis_snapshot (
    id varchar(36) primary key,
    project_id bigint not null,
    requirement_id bigint not null,
    requirement_version_id bigint not null,
    job_id varchar(36) not null,
    status varchar(32) not null,
    analysis_session_id varchar(64) not null,
    provider varchar(40),
    model_name varchar(160),
    prompt_fingerprint varchar(64),
    taxonomy_fingerprint varchar(64),
    workspace_id varchar(120),
    branch_name varchar(240),
    commit_sha varchar(64),
    created_by varchar(160) not null,
    created_at timestamp(6) with time zone not null,
    duration_ms bigint not null,
    warning_count integer not null,
    error_message varchar(2000),
    analysis_payload oid not null,
    gap_payload oid,
    pattern_payload oid,
    recommendation_payload oid,
    foreign key (project_id) references arch_project (id),
    foreign key (requirement_id) references project_requirement (id),
    foreign key (requirement_version_id) references project_req_version (id),
    foreign key (job_id) references req_analysis_job (id)
);
create index if not exists idx_snap_project on req_analysis_snapshot (project_id, created_at);
create index if not exists idx_snap_req on req_analysis_snapshot (requirement_id, created_at);
create index if not exists idx_snap_job on req_analysis_snapshot (job_id);

create table if not exists req_element_mapping (
    id bigint generated by default as identity primary key,
    snapshot_id varchar(36) not null,
    node_code varchar(80) not null,
    node_title varchar(500),
    taxonomy_root varchar(8) not null,
    direct_score integer not null,
    relevance float(53) not null,
    confidence float(53) not null,
    mapping_origin varchar(32) not null,
    hierarchy_path varchar(2000),
    presence_reason varchar(2000),
    selected_for_impact boolean not null,
    review_status varchar(32) not null,
    action_status varchar(32) not null,
    action_evidence varchar(2000),
    decision_by varchar(160),
    decision_at timestamp(6) with time zone,
    decision_comment varchar(2000),
    row_version bigint not null,
    constraint uq_elmap_snap_node unique (snapshot_id, node_code),
    foreign key (snapshot_id) references req_analysis_snapshot (id)
);
create index if not exists idx_elmap_snapshot on req_element_mapping (snapshot_id);
create index if not exists idx_elmap_node on req_element_mapping (node_code);
create index if not exists idx_elmap_action on req_element_mapping (action_status);

create table if not exists req_relation_mapping (
    id bigint generated by default as identity primary key,
    snapshot_id varchar(36) not null,
    source_code varchar(80) not null,
    target_code varchar(80) not null,
    relation_type varchar(64) not null,
    relation_origin varchar(64) not null,
    relation_category varchar(32),
    relevance float(53) not null,
    confidence float(53) not null,
    presence_reason varchar(2000),
    review_status varchar(32) not null,
    decision_by varchar(160),
    decision_at timestamp(6) with time zone,
    decision_comment varchar(2000),
    row_version bigint not null,
    constraint uq_relmap_signature unique (snapshot_id, source_code, target_code, relation_type, relation_origin),
    foreign key (snapshot_id) references req_analysis_snapshot (id)
);
create index if not exists idx_relmap_snapshot on req_relation_mapping (snapshot_id);
create index if not exists idx_relmap_source on req_relation_mapping (source_code);
create index if not exists idx_relmap_target on req_relation_mapping (target_code);

create table if not exists project_solution (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    solution_id bigint not null,
    status varchar(32) not null,
    action_status varchar(32) not null,
    priority integer not null,
    rationale varchar(2000),
    created_by varchar(160) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_psol_project_sol unique (project_id, solution_id),
    foreign key (project_id) references arch_project (id),
    foreign key (solution_id) references solution_definition (id)
);
create index if not exists idx_psol_project on project_solution (project_id);
create index if not exists idx_psol_status on project_solution (project_id, status);

create table if not exists req_solution_link (
    id bigint generated by default as identity primary key,
    project_solution_id bigint not null,
    requirement_id bigint not null,
    snapshot_id varchar(36),
    coverage_percent integer not null,
    solution_role varchar(32) not null,
    review_status varchar(32) not null,
    evidence varchar(2000),
    updated_by varchar(160) not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_rsl_solution_req unique (project_solution_id, requirement_id),
    foreign key (project_solution_id) references project_solution (id),
    foreign key (requirement_id) references project_requirement (id)
);
create index if not exists idx_rsl_req on req_solution_link (requirement_id);
create index if not exists idx_rsl_psol on req_solution_link (project_solution_id);

create table if not exists solution_taxonomy (
    id bigint generated by default as identity primary key,
    solution_id bigint not null,
    node_code varchar(80) not null,
    coverage_percent integer not null,
    evidence varchar(2000),
    review_status varchar(32) not null,
    updated_by varchar(160) not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_soltax_node unique (solution_id, node_code),
    foreign key (solution_id) references solution_definition (id)
);
create index if not exists idx_soltax_solution on solution_taxonomy (solution_id);
create index if not exists idx_soltax_node on solution_taxonomy (node_code);

create table if not exists product_taxonomy (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    node_code varchar(80) not null,
    coverage_percent integer not null,
    evidence varchar(2000),
    review_status varchar(32) not null,
    updated_by varchar(160) not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_prodtax_node unique (product_id, node_code),
    foreign key (product_id) references product_catalog (id)
);
create index if not exists idx_prodtax_product on product_taxonomy (product_id);
create index if not exists idx_prodtax_node on product_taxonomy (node_code);

create table if not exists solution_product (
    id bigint generated by default as identity primary key,
    project_solution_id bigint not null,
    product_id bigint not null,
    coverage_percent integer not null,
    hard_exclusions varchar(4000),
    strengths varchar(4000),
    weaknesses varchar(4000),
    open_evidence varchar(4000),
    confidence float(53) not null,
    review_status varchar(32) not null,
    selection_status varchar(32) not null,
    updated_by varchar(160) not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null,
    constraint uq_solprod_pair unique (project_solution_id, product_id),
    foreign key (project_solution_id) references project_solution (id),
    foreign key (product_id) references product_catalog (id)
);
create index if not exists idx_solprod_psol on solution_product (project_solution_id);
create index if not exists idx_solprod_product on solution_product (product_id);

create table if not exists project_conflict (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    requirement_a_id bigint not null,
    requirement_b_id bigint not null,
    conflict_type varchar(32) not null,
    status varchar(32) not null,
    fingerprint varchar(64) not null,
    title varchar(500) not null,
    evidence oid not null,
    confidence float(53) not null,
    resolution_note varchar(4000),
    detected_at timestamp(6) with time zone not null,
    reviewed_by varchar(160),
    reviewed_at timestamp(6) with time zone,
    row_version bigint not null,
    constraint uq_conf_signature unique (project_id, requirement_a_id, requirement_b_id, conflict_type, fingerprint),
    foreign key (project_id) references arch_project (id),
    foreign key (requirement_a_id) references project_requirement (id),
    foreign key (requirement_b_id) references project_requirement (id)
);
create index if not exists idx_conf_project on project_conflict (project_id, status);
create index if not exists idx_conf_req_a on project_conflict (requirement_a_id);
create index if not exists idx_conf_req_b on project_conflict (requirement_b_id);

alter table relation_hypothesis add column if not exists project_id bigint;
alter table relation_hypothesis add column if not exists requirement_id bigint;
alter table relation_hypothesis add column if not exists analysis_snapshot_id varchar(36);
create index if not exists idx_hyp_project on relation_hypothesis (project_id);
create index if not exists idx_hyp_requirement on relation_hypothesis (requirement_id);
create index if not exists idx_hyp_snapshot on relation_hypothesis (analysis_snapshot_id);
