-- Rebuildable branch-local relation decision projection.
--
-- JGit/TaxDSL remains authoritative. The projection records both presence and
-- removal tombstones so workspace and variant branches do not fall back to an
-- inherited central relation after a local removal.

CREATE TABLE relation_decision_projection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id VARCHAR(255) NOT NULL,
    workspace_id VARCHAR(255),
    workspace_scope_key VARCHAR(255) NOT NULL DEFAULT '__shared__',
    branch VARCHAR(255) NOT NULL,
    source_code VARCHAR(255) NOT NULL,
    relation_type VARCHAR(64) NOT NULL,
    target_code VARCHAR(255) NOT NULL,
    relation_present BOOLEAN NOT NULL,
    status VARCHAR(255),
    confidence DOUBLE PRECISION,
    provenance VARCHAR(255),
    authoritative_commit_id VARCHAR(40) NOT NULL,
    causation_id VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_relation_decision_projection_repository
        FOREIGN KEY (repository_id)
        REFERENCES system_repository (repository_id),
    CONSTRAINT uq_rel_decision_scope_identity
        UNIQUE (
            repository_id,
            workspace_scope_key,
            branch,
            source_code,
            relation_type,
            target_code
        ),
    CONSTRAINT ck_rel_decision_workspace_scope
        CHECK (
            (workspace_id IS NULL AND workspace_scope_key = '__shared__')
            OR (
                workspace_id IS NOT NULL
                AND BTRIM(workspace_id) <> ''
                AND workspace_scope_key = BTRIM(workspace_id)
            )
        ),
    CONSTRAINT ck_rel_decision_confidence
        CHECK (
            confidence IS NULL
            OR (confidence >= 0.0 AND confidence <= 1.0)
        )
);

CREATE INDEX idx_rel_decision_repository
    ON relation_decision_projection (repository_id);

CREATE INDEX idx_rel_decision_scope_branch
    ON relation_decision_projection (
        repository_id,
        workspace_scope_key,
        branch
    );

CREATE INDEX idx_rel_decision_commit
    ON relation_decision_projection (authoritative_commit_id);
