# Repository-owned license metadata overrides for packaged runtime dependencies.
#
# Key format:
# groupId--artifactId--version=Canonical license name
#
# The Maven build reads this file as an override database and never generates or
# deletes it. Add an entry only when the published dependency POM has no usable
# license metadata, after verifying the canonical upstream license and recording
# that evidence in the reviewing pull request.
