# Repository-owned license metadata overrides for packaged runtime dependencies.
#
# The Maven license gate writes missing entries here using this key format:
# groupId--artifactId--version=Canonical license name
#
# Keep this file limited to dependencies whose published Maven POM does not
# declare usable license metadata. Every entry must be verified against the
# upstream project's canonical license before it is committed.
